// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: like.sql

package db

import (
	"context"
)

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
    user_id, tweet_id
) VALUES (
    $1, $2
) RETURNING user_id, tweet_id, created_at
`

type CreateLikeParams struct {
	UserID  int64 `json:"user_id"`
	TweetID int64 `json:"tweet_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRow(ctx, createLike, arg.UserID, arg.TweetID)
	var i Like
	err := row.Scan(&i.UserID, &i.TweetID, &i.CreatedAt)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes WHERE user_id = $1 AND tweet_id = $2
`

type DeleteLikeParams struct {
	UserID  int64 `json:"user_id"`
	TweetID int64 `json:"tweet_id"`
}

func (q *Queries) DeleteLike(ctx context.Context, arg DeleteLikeParams) error {
	_, err := q.db.Exec(ctx, deleteLike, arg.UserID, arg.TweetID)
	return err
}

const getLikesByTweetID = `-- name: GetLikesByTweetID :many
SELECT user_id, tweet_id, created_at FROM likes WHERE tweet_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetLikesByTweetIDParams struct {
	TweetID int64 `json:"tweet_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) GetLikesByTweetID(ctx context.Context, arg GetLikesByTweetIDParams) ([]Like, error) {
	rows, err := q.db.Query(ctx, getLikesByTweetID, arg.TweetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(&i.UserID, &i.TweetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikesByUserID = `-- name: GetLikesByUserID :many
SELECT user_id, tweet_id, created_at FROM likes WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetLikesByUserIDParams struct {
	UserID int64 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLikesByUserID(ctx context.Context, arg GetLikesByUserIDParams) ([]Like, error) {
	rows, err := q.db.Query(ctx, getLikesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Like
	for rows.Next() {
		var i Like
		if err := rows.Scan(&i.UserID, &i.TweetID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
