// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	Email             string             `json:"email"`
	ProfilePictureUrl pgtype.Text        `json:"profile_picture_url"`
	Bio               pgtype.Text        `json:"bio"`
	LastLogin         pgtype.Timestamptz `json:"last_login"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	IsAdmin           bool               `json:"is_admin"`
	IsActive          bool               `json:"is_active"`
	LastDeactivatedAt pgtype.Timestamptz `json:"last_deactivated_at"`
	NFollowers        pgtype.Int4        `json:"n_followers"`
	NFollowing        pgtype.Int4        `json:"n_following"`
	NTweets           pgtype.Int4        `json:"n_tweets"`
}

type Follow struct {
	FollowerID  int64              `json:"follower_id"`
	FollowingID int64              `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Like struct {
	UserID    int64              `json:"user_id"`
	TweetID   int64              `json:"tweet_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reply struct {
	ID        int64              `json:"id"`
	TweetID   int64              `json:"tweet_id"`
	UserID    int64              `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Retweet struct {
	UserID    int64              `json:"user_id"`
	TweetID   int64              `json:"tweet_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Tweet struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	IsDeleted bool               `json:"is_deleted"`
	RetweetID pgtype.Int8        `json:"retweet_id"`
	NLikes    pgtype.Int4        `json:"n_likes"`
	NRetweets pgtype.Int4        `json:"n_retweets"`
	NReply    pgtype.Int4        `json:"n_reply"`
}
